### ISSUE TITLE
Use pre-defined error instances

### ISSUE THREAD

**Issue by shazow** [gogits/git#13]
Hiya, right now there are a bunch of `errors.New(fmt.Sprintf(...))` all over the code, and the string is often dynamic so it makes it hard to compare conditions programmatically.

For instance, when an object is not found: https://github.com/gogits/git/blob/16f4de6a9d8a6695826ef4118f58dff85174b335/repo_object.go#L81

I propose we pull out at least the more common errors into package variables so that the conditions can be compared against. We can still make the Error() messages dynamically generated, so the output will stay the same.

(Happy to work on a PR for this, just let me know!)

**Comment by Unknwon** [comment]
Hi there,

This repository is kind of suspend for maintenance, but may continue in the future.

Hmm... so the point is I don't want waste your time. :sweat:

**Comment by shazow** [comment]
Would you recommend not using this? Do you have suggestions for an alternative? Should I start my own fork? :)

**Comment by Unknwon** [comment]
> Would you recommend not using this?

Code most likely is not going to change.

> Should I start my own fork?

Yes, I think so.

**Comment by shazow** [comment]
Very well, thanks for letting me know, and thanks for the great work so far!

**Comment by Unknwon** [comment]
:trollface: Gogs currently is using git-shell, may come back to manipulate internal objects after 1.0 release when we got enough time
