### ISSUE TITLE
Buffer read change in Go 1.7 breaks readObjectFile()

### ISSUE THREAD

**Issue by snicol** [gogits/git#18]
I found that after upgrading to Go 1.7, `repo.GetCommitOfBranch(branch)` started returning an `EOF` and not the commit sha1 that I expected. 

https://github.com/gogits/git/blob/564c5fe86bbef8589421582b69657cc08c4c85fb/repo_utils.go#L306

I dug in and found that simply removing the error check fixes this, which matches up with the release notes below. 

> In previous releases of Go, if Reader's Read method were asked for zero bytes with no data remaining, it would return a count of 0 and no error. Now it returns a count of 0 and the error io.EOF

**Comment by lemmi** [comment]
this should at least check for the number of bytes read or use io.ReadFull or something. leaving out the check is probably not the right thing to do.

**Comment by snicol** [comment]
Definitely, I only removed the check to see if that change was the cause. I will submit a PR with the >0 bytes check 😊
